package ugh;
									/*
									DO NOT CHANGE THIS FILE, IT'S
									GENERATED BY MAVEN!
									*/
									public class UghCliVersion {
									public final
									static String VERSION =
									"1.9-SNAPSHOT";
									public final static
									String BUILDDATE =
									"7-May-2010";
									}