--
-- (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
--
-- This file is part of the Kitodo project.
--
-- It is licensed under GNU General Public License version 3 or later.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.
--
-- Migration: Add 'sorting' column to importconfiguration/mappingfile cross table
ALTER TABLE importconfiguration_x_mappingfile ADD sorting INT(11) DEFAULT 0;
