--
-- (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
--
-- This file is part of the Kitodo project.
--
-- It is licensed under GNU General Public License version 3 or later.
--
-- For the full copyright and license information, please read the
-- GPL3-License.txt file that was distributed with this source code.
--
-- Migration: Add 'prestructured_import' column to 'mappingfile' table
ALTER TABLE mappingfile ADD prestructured_import tinyint(1) DEFAULT 0;
