--
-- (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
--
-- This file is part of the Kitodo project.
--
-- It is licensed under GNU General Public License version 3 or later.
--
-- For the full copyright and license information, please read the
-- GPL3-License.txt file that was distributed with this source code.
--
-- Migration: Add 'identifier_metadata' column to importconfiguration
ALTER TABLE importconfiguration ADD identifier_metadata varchar(255) NOT NULL DEFAULT 'CatalogIDDigital';
