--
-- (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
--
-- This file is part of the Kitodo project.
--
-- It is licensed under GNU General Public License version 3 or later.
--
-- You should have received a copy of the GNU General Public License
-- along with this program.  If not, see <https://www.gnu.org/licenses/>.
--
-- Migration: drop 'identifier_metadata' column from 'importconfiguration' table (replaced by functional metadata in
--            ruleset)
ALTER TABLE importconfiguration DROP identifier_metadata;
