/*
 * (c) Kitodo. Key to digital objects e. V. <contact@kitodo.org>
 *
 * This file is part of the Kitodo project.
 *
 * It is licensed under GNU General Public License version 3 or later.
 *
 * For the full copyright and license information, please read the
 * GPL3-License.txt file that was distributed with this source code.
 */
package org.kitodo.production.lugh;

import static org.junit.Assert.assertEquals;

import java.io.*;
import java.net.*;
import java.util.*;

import org.junit.Test;
import org.kitodo.production.lugh.ld.*;

public class AuthorityFileUtilTest {

    @Test
    public void testDataURLForRecordURIWithTailConfigured() throws MalformedURLException {
        Map<String, String> config = new HashMap<>();
        config.put("authority.gnd.dataUrlTail", "/about/lds.rdf");
        config.put("namespace.gnd", "http://d-nb.info/gnd/");
        assertEquals(
            new URL("http://d-nb.info/gnd/118514768/about/lds.rdf"),
            AuthorityFileUtil.dataURLForRecordURI("http://d-nb.info/gnd/118514768", config)
        );
    }

    @Test
    public void testDataURLForRecordURIWithoutTail() throws MalformedURLException {
        Map<String, String> config = new HashMap<>();
        config.put("authority.http://d-nb.info/gnd/.dataUrlTail", "/about/lds.rdf");
        assertEquals(
            new URL("http://d-nb.info/gnd/118514768/about/lds.rdf"),
            AuthorityFileUtil.dataURLForRecordURI("http://d-nb.info/gnd/118514768", config)
        );
    }

    @Test
    public void testNodeFromInputStream() throws URISyntaxException, LinkedDataException, IOException {

        String base = new URL("http://d-nb.info/gnd/118514768/about/lds.rdf").toURI().toASCIIString();
        String gnd118514768 = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<rdf:RDF\n"
                + "\txmlns:schema=\"http://schema.org/\"\n"
                + "\txmlns:gndo=\"http://d-nb.info/standards/elementset/gnd#\"\n"
                + "\txmlns:lib=\"http://purl.org/library/\"\n"
                + "\txmlns:marcRole=\"http://id.loc.gov/vocabulary/relators/\"\n"
                + "\txmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "\txmlns:skos=\"http://www.w3.org/2004/02/skos/core#\"\n"
                + "\txmlns:dcmitype=\"http://purl.org/dc/dcmitype/\"\n"
                + "\txmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "\txmlns:geo=\"http://www.opengis.net/ont/geosparql#\"\n"
                + "\txmlns:umbel=\"http://umbel.org/umbel#\"\n\txmlns:dbp=\"http://dbpedia.org/property/\"\n"
                + "\txmlns:dnbt=\"http://d-nb.info/standards/elementset/dnb#\"\n"
                + "\txmlns:rdau=\"http://rdaregistry.info/Elements/u/\"\n"
                + "\txmlns:sf=\"http://www.opengis.net/ont/sf#\"\n\txmlns:dnb_intern=\"http://dnb.de/\"\n"
                + "\txmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "\txmlns:v=\"http://www.w3.org/2006/vcard/ns#\"\n\txmlns:dcterms=\"http://purl.org/dc/terms/\"\n"
                + "\txmlns:bibo=\"http://purl.org/ontology/bibo/\"\n"
                + "\txmlns:gbv=\"http://purl.org/ontology/gbv/\"\n"
                + "\txmlns:isbd=\"http://iflastandards.info/ns/isbd/elements/\"\n"
                + "\txmlns:foaf=\"http://xmlns.com/foaf/0.1/\"\n\txmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n"
                + "<rdf:Description rdf:about=\"http://d-nb.info/gnd/118514768\">\n"
                + "\t<rdf:type rdf:resource=\"http://d-nb.info/standards/elementset/gnd#DifferentiatedPerson\"/>\n"
                + "\t<foaf:page rdf:resource=\"http://de.wikipedia.org/wiki/Bertolt_Brecht\"/>\n"
                + "\t<owl:sameAs rdf:resource=\"http://dbpedia.org/resource/Bertolt_Brecht\"/>\n"
                + "\t<owl:sameAs rdf:resource=\"http://viaf.org/viaf/2467372\"/>\n"
                + "\t<gndo:gndIdentifier rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">118514768</gndo:gndIdentifier>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588)1022091077</gndo:oldAuthorityNumber>\n"
                + "\t<owl:sameAs rdf:resource=\"http://d-nb.info/gnd/1022091077\"/>\n"
                + "\t<dnbt:deprecatedUri rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">http://d-nb.info/gnd/1022091077</dnbt:deprecatedUri>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)118514768</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)141399074</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)139089691</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)141300248</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)136949541</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)134336232</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)12794544X</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)12736630X</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)12722811X</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)127228098</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:oldAuthorityNumber rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">(DE-588a)127228101</gndo:oldAuthorityNumber>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brêcht, Becton</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516048\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Becton</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brêcht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolʹ</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516049\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertolʹ</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, B.</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516050\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">B.</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Eugen Berthold Friedrich</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516051\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Eugen Berthold Friedrich</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, ...</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516052\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">...</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht-Eisler, ...</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516053\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">...</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht-Eisler</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Beituo'erte-Bulaixite</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516054\">\n"
                + "\t\t\t<gndo:personalName rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Beituo'erte-Bulaixite</gndo:personalName>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berchito, B.</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516055\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">B.</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berchito</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brechtas, B.</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516056\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">B.</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brechtas</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brechts, Bertolts</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516057\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertolts</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brechts</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brehts, Bertolts</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516058\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertolts</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brehts</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breḳhṭ, Bārṭolṭ</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516059\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bārṭolṭ</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breḳhṭ</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekt, Berṭolṭ</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516060\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berṭolṭ</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekt</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekṭ, Berṭōlṭ</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516061\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berṭōlṭ</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekṭ</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breḳṭ, Berṭôlṭ</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516062\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berṭôlṭ</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breḳṭ</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breśṭ, Berṭalṭa</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516063\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berṭalṭa</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breśṭ</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breṣṭa, Barṭolṭa</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516064\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Barṭolṭa</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breṣṭa</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brišt, Bartūlt</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516065\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bartūlt</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brišt</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brišt, Birtūld</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516066\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Birtūld</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brišt</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brišt, Birtult</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516067\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Birtult</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brišt</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brīḫt, Birtūld</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516068\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Birtūld</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brīḫt</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Buchito, Berutorutu</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516069\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berutorutu</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Buchito</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bulaixite, Beituo'erte</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516070\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Beituo'erte</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bulaixite</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bulaixite, ...</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516071\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">...</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bulaixite</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Burehito, Berutoruto</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516072\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berutoruto</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Burehito</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Burehito, ...</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516073\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">...</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Burehito</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">B. B.</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516074\">\n"
                + "\t\t\t<gndo:personalName rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">B. B.</gndo:personalName>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Mprecht, ...</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516075\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">...</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Mprecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Pulaihsit'ê, Peit'oĉrht'ê</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516076\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Peit'oĉrht'ê</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Pulaihsit'ê</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Pulaihsit'ê, ...</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516077\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">...</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Pulaihsit'ê</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Pŭrehit'ŭ, Peŏt'olt'ŭ</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516078\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Peŏt'olt'ŭ</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Pŭrehit'ŭ</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bŭrehit'ŭ, Beŏt'olt'ŭ</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516079\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Beŏt'olt'ŭ</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bŭrehit'ŭ</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Berthold</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516080\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berthold</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Becht, Bertolt</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516081\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertolt</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Becht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brehd, Berd</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516082\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berd</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brehd</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Larsen, Berthold</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516083\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berthold</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Larsen</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekt, Bertôlt</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516084\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertôlt</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekt</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekht, Bartolt</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516085\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bartolt</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brist, Birtult</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516086\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Birtult</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brist</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bert</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516087\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bert</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bresta, Bartolta</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516088\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bartolta</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bresta</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bert</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516089\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bert</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertholt</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516090\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertholt</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertold</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516091\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertold</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breht, Bertolt</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516092\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertolt</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Mprecht, Mpertolt</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516093\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Mpertolt</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Mprecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Eugen Berthold Friedrich</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516094\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Eugen Berthold Friedrich</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekht, Bertolʹt</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516095\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertolʹt</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekht, Bertolʹd</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516096\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertolʹd</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brekht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breḵṭ, Berṭolṭ</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516097\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Berṭolṭ</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Breḵṭ</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Eugen Bertolt Friedrich</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516098\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Eugen Bertolt Friedrich</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">برشت، برتولد</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516099\">\n"
                + "\t\t\t<gndo:personalName rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">برشت، برتولد</gndo:personalName>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">브레히트, 베르톨트</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516100\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">베르톨트</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">브레히트</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">ברכט, ברטולט</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516101\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">ברטולט</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">ברכט</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">贝·布莱希特</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516102\">\n"
                + "\t\t\t<gndo:personalName rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">贝·布莱希特</gndo:personalName>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">布莱希特, 贝</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516103\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">贝</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">布莱希特</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:variantNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">ブレヒト, ベルトルト</gndo:variantNameForThePerson>\n"
                + "\t<gndo:variantNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516104\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">ベルトルト</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">ブレヒト</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:variantNameEntityForThePerson>\n"
                + "\t<gndo:preferredNameForThePerson rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolt</gndo:preferredNameForThePerson>\n"
                + "\t<gndo:preferredNameEntityForThePerson>\n"
                + "\t\t<rdf:Description rdf:nodeID=\"node1b7pkqtcbx516105\">\n"
                + "\t\t\t<gndo:forename rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Bertolt</gndo:forename>\n"
                + "\t\t\t<gndo:surname rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht</gndo:surname>\n"
                + "\t\t</rdf:Description>\n\t</gndo:preferredNameEntityForThePerson>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/121608557\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/119056011\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/118738348\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/137070411\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/118809849\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/119027615\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/118940163\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/118630091\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/123783283\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/118940155\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/110005449\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/13612495X\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/123757398\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/1030496250\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/1030496366\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/1072228688\"/>\n"
                + "\t<gndo:familialRelationship rdf:resource=\"http://d-nb.info/gnd/134772350\"/>\n"
                + "\t<gndo:professionOrOccupation rdf:resource=\"http://d-nb.info/gnd/4053309-8\"/>\n"
                + "\t<gndo:professionOrOccupation rdf:resource=\"http://d-nb.info/gnd/4185053-1\"/>\n"
                + "\t<gndo:professionOrOccupation rdf:resource=\"http://d-nb.info/gnd/4140241-8\"/>\n"
                + "\t<gndo:professionOrOccupation rdf:resource=\"http://d-nb.info/gnd/4052154-0\"/>\n"
                + "\t<gndo:professionOrOccupation rdf:resource=\"http://d-nb.info/gnd/4168391-2\"/>\n"
                + "\t<gndo:professionOrOccupation rdf:resource=\"http://d-nb.info/gnd/4049050-6\"/>\n"
                + "\t<gndo:professionOrOccupation rdf:resource=\"http://d-nb.info/gnd/4294338-3\"/>\n"
                + "\t<gndo:gndSubjectCategory rdf:resource=\"http://d-nb.info/standards/vocab/gnd/gnd-sc#12.2p\"/>\n"
                + "\t<gndo:gndSubjectCategory rdf:resource=\"http://d-nb.info/standards/vocab/gnd/gnd-sc#15.1p\"/>\n"
                + "\t<gndo:gndSubjectCategory rdf:resource=\"http://d-nb.info/standards/vocab/gnd/gnd-sc#15.3p\"/>\n"
                + "\t<gndo:geographicAreaCode rdf:resource=\"http://d-nb.info/standards/vocab/gnd/geographic-area-code#XA-DE\"/>\n"
                + "\t<gndo:languageCode rdf:resource=\"http://id.loc.gov/vocabulary/iso639-2/ger\"/>\n"
                + "\t<gndo:publication rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolt: Dreigroschenroman. - 1934</gndo:publication>\n"
                + "\t<gndo:publication rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolt: Hauspostille. - 1927</gndo:publication>\n"
                + "\t<gndo:publication rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolt: Aufstieg und Fall der Stadt Mahagonny. - 1929</gndo:publication>\n"
                + "\t<gndo:publication rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolt: Baal. - 1922</gndo:publication>\n"
                + "\t<gndo:publication rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolt: Trommeln in der Nacht. - 1923</gndo:publication>\n"
                + "\t<gndo:publication rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolt: Mann ist Mann. - 1926</gndo:publication>\n"
                + "\t<gndo:publication rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolt: Im Dickicht der Städte. - 1927</gndo:publication>\n"
                + "\t<gndo:publication rdf:datatype=\"http://www.w3.org/2001/XMLSchema#string\">Brecht, Bertolt: Furcht und Elend des III. Reiches. - 1945</gndo:publication>\n"
                + "\t<gndo:biographicalOrHistoricalInformation xml:lang=\"de\">Schriftsteller, Regisseur</gndo:biographicalOrHistoricalInformation>\n"
                + "\t<gndo:placeOfBirth rdf:resource=\"http://d-nb.info/gnd/4003614-5\"/>\n"
                + "\t<gndo:placeOfDeath rdf:resource=\"http://d-nb.info/gnd/4005728-8\"/>\n"
                + "\t<gndo:placeOfExile rdf:resource=\"http://d-nb.info/gnd/4010877-6\"/>\n"
                + "\t<gndo:placeOfExile rdf:resource=\"http://d-nb.info/gnd/4077258-5\"/>\n"
                + "\t<owl:sameAs rdf:resource=\"http://www.filmportal.de/person/261E2D3A93D54134BF8AB5F21F0B2399\"/>\n"
                + "\t<gndo:gender rdf:resource=\"http://d-nb.info/standards/vocab/gnd/gender#male\"/>\n"
                + "\t<gndo:dateOfBirth rdf:datatype=\"http://www.w3.org/2001/XMLSchema#date\">1898-02-10</gndo:dateOfBirth>\n"
                + "\t<gndo:dateOfDeath rdf:datatype=\"http://www.w3.org/2001/XMLSchema#date\">1956-08-14</gndo:dateOfDeath>\n"
                + "</rdf:Description>\n\n</rdf:RDF>\n";

        Node result;
        try (InputStream HANDLE = new ByteArrayInputStream(gnd118514768.getBytes("UTF-8"))) {
            result = AuthorityFileUtil.nodeFromInputStream(HANDLE, base);
        }

        assertEquals(12, result.get("http://d-nb.info/standards/elementset/gnd#oldAuthorityNumber").size());
        assertEquals(
            "Brecht, Bertolt",
            result.get("http://d-nb.info/standards/elementset/gnd#preferredNameForThePerson").strings(" ; ", false)
        );
        assertEquals(4, result.get("http://www.w3.org/2002/07/owl#sameAs").size());
        assertEquals(55, result.get("http://d-nb.info/standards/elementset/gnd#variantNameForThePerson").size());
    }
}
